service: serverlessLamda-api2
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  iam:
     role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:*'
          Resource:
            -  'arn:aws:dynamodb:us-east-1:683883881884:table/*'
 

functions:
  hello:
    handler: handler.curdOps
    events:
      - http:
          path: /items/{id}
          method: get
      - http:
          path: /items
          method: put
      - http:
          path: /items/{id}
          method: delete
      - http:
          path: /items
          method: post
